update scripts

diff --git a/_johnko-bin/usr/local/bin/keypkg-setup b/_johnko-bin/usr/local/bin/keypkg-setup
--- a/_johnko-bin/usr/local/bin/keypkg-setup
+++ b/_johnko-bin/usr/local/bin/keypkg-setup
@@ -13,6 +13,14 @@ KGT_DATA_AUTO_SIZE=1
 KGT_SECTOR_SIZE=4096
 KGT_NEW_POOL_NAME="tank"
 KGT_VDEV_TYPE=""
+KGT_TMPFS=/tmp/tmpfs
+NEWPASSFILE=${KGT_TMPFS}/geli_password.txt
+KGT_KEYPKGDIR=/etc/keypkg
+KGT_KEYPKGKEY=${KGT_KEYPKGDIR}/key.pem
+KGT_KEYPKGPUBCERT=${KGT_KEYPKGDIR}/cert.pem
+KGT_KEYSIZE=8192
+KGT_KEYTYPE=rsa
+keypkg_ssh_config="/etc/keypkg/ssh_config"
 
 usage() {
     cat <<EOF
@@ -44,6 +52,16 @@ runorerror() {
     $@ || exiterror $? $@
 }
 
+mount_tmpfsdir() {
+    mkdir -p $KGT_TMPFS
+    chmod 700 $KGT_TMPFS
+    mount -t tmpfs tmpfs $KGT_TMPFS
+    if ! mount | grep 'tmpfs on /tmp/tmpfs (tmpfs' >/dev/null 2>&1 ; then
+        exit 1
+    fi
+    touch $NEWPASSFILE
+    chmod 600 $NEWPASSFILE
+}
 
 if [ $# -eq 0 ]; then
     usage ; exiterror 1
@@ -73,18 +91,64 @@ if [ "yes" != "$ismounted" ]; then
     exiterror 1 "Pool $KGT_KEY_POOL_NAME is not mounted."
 fi
 
-# Prompt for geli passphrase
-stty -echo
-printf "GELI Encryption Passphrase:"
-read PASSWORD
-
-# write passphrase to "/key_mountpoint/geli_password.txt"
 mountdir=$( zfs list -H -o mountpoint $KGT_KEY_POOL_NAME )
-NEWPASSFILE=${mountdir}/geli_password.txt
-echo $PASSWORD >$NEWPASSFILE
-if [ ! -e $NEWPASSFILE ]; then
-    exiterror 1 "Failed to save passphrase to $NEWPASSFILE."
+ENCPASSFILE=${mountdir}/keypkg_$(hostname -s).smime
+
+# create /etc/keypkg
+install -d -m 0700 -o root -g wheel $KGT_KEYPKGDIR
+chmod 0700 $KGT_KEYPKGDIR
+chown root:wheel $KGT_KEYPKGDIR
+# generate key if not exist
+if [ ! -e $KGT_KEYPKGPUBCERT ]; then
+    echo "Generating a $KGT_KEYSIZE bit $KGT_KEYTYPE private key. Please wait..."
+    yes '' | openssl req -x509 -nodes -days 36500 -newkey $KGT_KEYTYPE:$KGT_KEYSIZE \
+        -keyout $KGT_KEYPKGKEY -out $KGT_KEYPKGPUBCERT 2>/dev/null
+    chmod 400 $KGT_KEYPKGKEY
+    chmod 400 $KGT_KEYPKGPUBCERT
 fi
+
+if [ ! -e $ENCPASSFILE ]; then
+    # Prompt for geli passphrase
+    stty -echo
+    printf "GELI Encryption Passphrase:"
+    read PASSWORD
+
+    # newline
+    echo
+
+    # write passphrase to "$KGT_TMPFS/geli_password.txt" to be encrypted
+    mount_tmpfsdir
+    echo $PASSWORD >$NEWPASSFILE
+    if [ ! -e $NEWPASSFILE ]; then
+        exiterror 1 "Failed to save passphrase to $NEWPASSFILE."
+    fi
+    # encrypt $NEWPASSFILE to $ENCPASSFILE
+    openssl smime -sign -binary -nodetach -nocerts \
+        -signer $KGT_KEYPKGPUBCERT -inkey $KGT_KEYPKGKEY \
+        -in $NEWPASSFILE \
+            | openssl smime -encrypt -aes-256-cbc $KGT_KEYPKGPUBCERT \
+            | openssl smime -sign -binary -nodetach -nocerts \
+                -signer $KGT_KEYPKGPUBCERT -inkey $KGT_KEYPKGKEY \
+                -out $ENCPASSFILE
+    chmod 600 $ENCPASSFILE
+    # unmount so we lose "$KGT_TMPFS/geli_password.txt"
+    umount -f $KGT_TMPFS
+fi
+
+# Verify package was for self
+if ! openssl smime -verify -CAfile $KGT_KEYPKGPUBCERT -certfile $KGT_KEYPKGPUBCERT \
+        -in $ENCPASSFILE >/dev/null 2>/dev/null ; then
+    echo "Verification of $ENCPASSFILE failed."
+    exit 1
+fi
+# Decrypt ENCPASSFILE to KGT_TMPFS to make sure it works
+mount_tmpfsdir
+openssl smime -verify -CAfile $KGT_KEYPKGPUBCERT -certfile $KGT_KEYPKGPUBCERT \
+    -in $ENCPASSFILE 2>/dev/null \
+        | openssl smime -decrypt -binary -nointern -recip $KGT_KEYPKGPUBCERT -inkey $KGT_KEYPKGKEY \
+        | openssl smime -verify -CAfile $KGT_KEYPKGPUBCERT -certfile $KGT_KEYPKGPUBCERT \
+            -out $NEWPASSFILE 2>/dev/null
+chmod 600 $NEWPASSFILE
 
 # add data partitions to disks
 echo "Creating data partitions ..."
@@ -124,7 +188,7 @@ vdevs=""
 for disk in ${GPARTS}; do
     echo -n " ${disk}"
     # init
-    runorerror "geli init -e AES-XTS -J $NEWPASSFILE -s $KGT_SECTOR_SIZE ${disk}"
+    runorerror "geli init -e AES-XTS -l 256 -J $NEWPASSFILE -s $KGT_SECTOR_SIZE ${disk}"
     # remove boot flag
     runorerror "geli configure -B ${disk}"
     # attach
@@ -136,6 +200,8 @@ EOF
     vdevs="${vdevs} ${disk}.eli"
 done
 
+umount -f $KGT_TMPFS
+
 count=$( echo "${vdevs}" | wc -w | awk '{ print $1 }' )
 if [ "${count}" -gt "2" -a "${KGT_VDEV_TYPE}" != "mirror" ]; then
     KGT_VDEV_TYPE="mirror"
@@ -143,8 +209,28 @@ fi
 # create new pool
 runorerror "zpool create -O compress=lz4 -O atime=off $KGT_NEW_POOL_NAME $KGT_VDEV_TYPE $vdevs"
 
-# enable zpoolimportthengeli in rc.conf
-runorerror "sysrc -f /etc/rc.conf.d/zpoolimportthengeli zpoolimportthengeli_enable=YES"
-runorerror "sysrc -f /etc/rc.conf.d/zpoolimportthengeli zpoolimportthengeli_zpool=$KGT_KEY_POOL_NAME"
+# enable keypkg in rc.conf
+runorerror "install -C -m 755 /root/git/freebsd-install-script/etc/rc.d/keypkg ${FZG_MNT}/etc/rc.d/keypkg"
+runorerror "sysrc -f /etc/rc.conf.d/keypkg keypkg_enable=YES"
+runorerror "sysrc -f /etc/rc.conf.d/keypkg keypkg_zpool=$KGT_KEY_POOL_NAME"
+runorerror "sysrc -f /etc/rc.conf.d/keypkg keypkg_file=keypkg_$(hostname -s).smime"
+cat >>/etc/rc.conf.d/keypkg <<EOF
+# keypkg_ssh="one two three"
+keypkg_ssh_flags="-i /etc/keypkg/id_rsa -F $keypkg_ssh_config -o UserKnownHostsFile=/etc/keypkg/known_hosts"
+EOF
+cat >>$keypkg_ssh_config <<EOF
+Host one
+    Hostname keyserver1
+    Port 6371
+    User $(hostname -s)
+Host two
+    Hostname keyserver2
+    Port 6371
+    User $(hostname -s)
+Host three
+    Hostname headnode
+    Port 6371
+    User $(hostname -s)
+EOF
 
 echo "Reboot to test."
